#!/usr/bin/env zsh

# image width height
width=2048
height=1024
nbsteps=512
xpos="-1.45203"
ypos="0"
size="0.0001"
filename="mandelbrot.png"

PARAMS="$width $height $nbsteps $xpos $ypos $size $filename"

eval time ./mandelbrot $PARAMS
