#!/usr/bin/env zsh

# image width height
width=2560
height=1440
nbsteps=22000
xpos="-1.45205"
ypos="0.00001"
size="0.00005"
filename="mandelbrot2.png"

PARAMS="$width $height $nbsteps $xpos $ypos $size $filename"

eval time ./mandelbrot $PARAMS
