#!/usr/bin/env zsh

nbcore=4

# arguments are:
#   width nb pixels
#   height nb pixels
#   nb of iterations
#   x position
#   y position
#   with of the window

# \rm -f mandel.png && ./mandelbrot 500 200 256 -1.351 0.06 0.0005 mandel.png

dir=stillimages
[[ ! -e $dir ]] && mkdir $dir

old=( $dir/*(.N) )
(( $#old > 0 )) && {
    print -- "cleaning..."
    \rm -f $dir/*(.)
}

# posx=-1.2535555
# posy=0.3845245 
posx=-1.768573656315270993281742915329544712934120053405549882337511135282776553364635382
posy=-0.000964296851358280000176242720373819448274776122656563565285

liste=()
i=1
width=8.0
imgheight=500
imgwidth=$((imgheight*16/10))
while ((width>0.00000005)); do
    fic=$(printf "$dir/m-%04d.png" $i)
    \rm -f $fic
    PREPARAMS="$imgwidth $imgheight 1000 $posx $posy $width $fic"
    print ./mandelbrot $PREPARAMS
    eval ./mandelbrot +RTS -N$nbcore -RTS $PREPARAMS
    (($?>0)) && exit 0
    liste=( $liste $fic )
    (( width *= 0.95 ))
    ((i++))
done

cmd=avconv
which $cmd >/dev/null || cmd=ffmpeg
framerate=24
quality=8
\rm -f animandel.mpeg && \
$cmd -f image2 -i "$dir/m-%04d.png" -r $framerate -qscale $quality -s ${imgwidth}x${imgheight} animandel.mp4
# convert -delay 10 -loop 0 $liste animandel.gif
